# EXAMPLE FILE - FOR REFERENCE ONLY

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: modern-devops
type: Opaque
stringData:
  POSTGRES_USER: "example_user"
  POSTGRES_PASSWORD: "example_password"
